### ISSUE TITLE
FFmpeg  lib compile without SDL and X265 support on windows xp

### ISSUE THREAD

**Issue by gaohzwork** [Reino17/ffmpeg-windows-build-helpers#3]
Hello, now I met a problem. I can't run an application on Windows XP. The application is  developed with FFmpeg ,i see your information can recompile FFmpeg to support its run on Windows XP, I have downloaded your compiled library, but it can't run, because I need to compile FFmpeg with SDL and X265,    can you give me an idea or compile a lib for me?
Grateful!

**Comment by Reino17** [comment]
I'm sorry, but I'm at a complete loss here.
First of all you named the title _"FFmpeg lib compile **without** SDL and X265 support on windows xp"_, yet you say you need FFmpeg **with** SDL and x265. What is it?
> I can't run an application on Windows XP. The application is developed with FFmpeg

You can't run _an_ application. That's very vague.
I provide FFmpeg binaries. I can't help you with _some_ program that uses FFmpeg.

**Comment by gaohzwork** [comment]
Thank you very much for your reply!

(1) I need ffmpeg With SDL and X265，that can be supported on windows xp.I have downloaded your compiled ffmpeg binaries from your website,but i can not find SDL's support.
(2) I will solve the application's problem  by myself.

**Comment by Reino17** [comment]
My FFmpeg binaries are already built with SDL ('ffplay.exe' needs it) and x265. I'm not sure I understand why you opened this issue.
