### ISSUE TITLE
[Question] Is it possible to cross-compile this on a Linux system

### ISSUE THREAD

**Issue by nicolaasjan** [Reino17/ffmpeg-windows-build-helpers#4]
Greetings!

I'm trying to cross-compile this on a 64-bit Linux system.
Is that even possible with this script?

In the past I could successfully build ffmpeg with the script from Roger Pack, where you forked this from.
(disclaimer: I'm not a programmer)

The toolchain seemed to build successfully., but shortly after that I got this:

```
./cross_compile_ffmpeg.sh
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: Bestand of map bestaat niet
touch: kan tijdsstempels van '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.done' niet wijzigen: Bestand of map bestaat niet
wo 14 jun 2023 10:31:59 CEST
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within /media/ext3-data/git/ffmpeg-windows-build-helpers/ffmpeg_local_builds/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
MinGW-w64 compilers for Win32 already installed, not re-installing.

Starting 32-bit builds.

Local mingw-std-threads_git is up-to-date.
Configuring cmake-3.25.1 as "--prefix=/usr -- -DBUILD_CursesDialog=0 -DBUILD_TESTING=0".
---------------------------------------------
CMake 3.25.1, Copyright 2000-2022 Kitware, Inc. and Contributors
Found GNU toolchain
---------------------------------------------
Error when bootstrapping CMake:
Cannot find appropriate C compiler on this system.
Please specify one using environment variable CC.
See cmake_bootstrap.log for compilers attempted.

---------------------------------------------
Log of errors: /media/ext3-data/git/ffmpeg-windows-build-helpers/ffmpeg_local_builds/sandbox/win32/cmake-3.25.1/Bootstrap.cmk/cmake_bootstrap.log

```
From cmake_bootstrap.log:

```
cc1: error: CPU you selected does not support x86-64 instruction set
cc1: error: ‘-fcf-protection=full’ is not supported for this target
Test failed to compile
```

What am I missing here?

**Comment by nicolaasjan** [comment]
Never mind. 😀️

It went on after changing line:
`original_cflags='-O2 -march=pentium3 -mtune=athlon-xp -mfpmath=sse -msse'` 
to:
`original_cflags='-O2 -march=haswell -mfpmath=sse -msse'`

**But:**

```
CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_C_COMPILER:

    /media/ext3-data/git/ffmpeg-windows-build-helpers/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_CXX_COMPILER:

    /media/ext3-data/git/ffmpeg-windows-build-helpers/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-g++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```
So obviously it is looking for `.exe` files, which are not present of course.

Conclusion:
This script will only run on Windows?

**Comment by Reino17** [comment]
Hello nicolaasjan.

I did fork this from Roger Pack years ago, yes, but along the way I've removed a lot of (for me) unnecessary code, like Linux stuff and everything 64-bit. It's tailored to me (old) system.

But if you're looking to compile 64-bit binaries, I don't understand why you're looking at my script in the first place.

**Comment by nicolaasjan** [comment]
> But if you're looking to compile 64-bit binaries, I don't understand why you're looking at my script in the first place.

No, I wanted to see if I could build the 32-bit for Windows XP myself on Linux. 🙂

B.t.w., during my failed attempt it installed `nasm` and `cmake` in my Linux root, instead of in the sandbox.
So, I had to restore my system to a previous Timeshift snapshot.

I will close this issue, since it's now obvious it won't work for me.
Maybe it will work in a Windows XP VM?

**Comment by Reino17** [comment]
> _B.t.w., during my failed attempt it installed `nasm` and `cmake` in my Linux root, instead of in the sandbox._

When I forked this script [6 years ago](https://github.com/rdp/ffmpeg-windows-build-helpers/issues/219#issuecomment-306066471), Roger Pack was still using Cygwin and I haven't changed that, because... well, WinXP obviously doesn't have Windows Subsystem for Linux.

This fork was and is primarily for my old system to compile FFmpeg binaries **on** and **for** WinXP in a Linux environment (Cygwin). You'd obviously have to make a lot of adjustments if you want to make it work in any other situation / environment.
