### ISSUE TITLE
GSM 6.10 encoder is disabled

### ISSUE THREAD

**Issue by heretic13** [Reino17/ffmpeg-windows-build-helpers#5]
ffmpeg.exe -codecs | wsl grep gsm

ffmpeg version N-109535-gfcd557a-Reino Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10.4.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --prefix=/cygdrive/s/ffmpeg-windows-build-helpers-master/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --cross-prefix=/cygdrive/s/ffmpeg-windows-build-helpers-master/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --extra-cflags='-O2 -march=pentium3 -mtune=athlon-xp -mfpmath=sse -msse' --enable-shared --disable-static --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Reino --enable-gpl --enable-gray --enable-version3 --disable-bcrypt --disable-debug --disable-doc --disable-htmlpages --disable-manpages --disable-mediafoundation --disable-podpages --disable-txtpages --disable-w32threads --enable-avisynth --enable-frei0r --enable-filter=frei0r --enable-gmp --enable-libaom --enable-libass --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libsoxr --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-mbedtls
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 56.100 / 59. 56.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 53.100 /  8. 53.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
 D.AIL. gsm                  GSM
 D.AIL. gsm_ms               GSM Microsoft variant

Please add gsm 6.10 encoder

**Comment by Reino17** [comment]
I don't think my binaries are for you. If you're using WSL, then you're not on WinXP. You'd better get your binaries [here](https://www.gyan.dev/ffmpeg/builds/).
